const baseTheme = {
  colors: {
    primary: 'rgb(164, 120, 64)',
    success: 'rgb(37, 211, 102)',
    white: 'rgb(255, 255, 255)',
    background: 'rgb(41, 45, 52)',
    backgroundAlt: 'rgb(46, 47, 62)',
    surface: 'rgb(46, 47, 62)',
    surfaceDark: 'rgb(41, 45, 52)',
    textPrimary: 'rgb(255, 255, 255)',
    textSecondary: 'rgb(175, 177, 189)',
    textInverse: 'rgb(255, 255, 255)',
    border: 'rgb(164, 120, 64)',
    overlay: 'rgba(0, 0, 0, 0.3)',
  },
  spacing: {
    xs: 5,
    sm: 10,
    md: 15,
    lg: 20,
    xl: 35,
    section: 150,
  },
  typography: {
    families: {
      heading: 'Exo',
      body: 'Open Sans',
      system: 'Tahoma',
    },
    sizes: {
      display: 56,
      h1: 35,
      h2: 21,
      h3: 19.6,
      body: 14,
      caption: 11.2,
      tiny: 10,
    },
    weights: {
      thin: '200',
      light: '300',
      regular: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
    },
  },
  radius: {
    none: 0,
    sm: 4.2,
    md: 10,
    lg: 44.8,
    full: 999,
  },
  shadows: {
    none: {
      shadowColor: 'transparent',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    low: {
      shadowColor: 'rgba(0, 0, 0, 0.15)',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 1,
      shadowRadius: 0,
      elevation: 1,
    },
    medium: {
      shadowColor: 'rgba(0, 0, 0, 0.15)',
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 1,
      shadowRadius: 15,
      elevation: 5,
    },
    elevated: {
      shadowColor: 'rgba(0, 0, 0, 0.15)',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 1,
      shadowRadius: 30,
      elevation: 10,
    },
  },
};

export const theme = {
  ...baseTheme,
  colors: {
    ...baseTheme.colors,
    transparent: 'transparent',
    backdrop: baseTheme.colors.overlay,
    divider: 'rgba(255, 255, 255, 0.66)',
    card: baseTheme.colors.backgroundAlt,
    accentSoft: 'rgba(164, 120, 64, 0.12)',
    inputFill: baseTheme.colors.surface,
    navSurface: 'rgba(41, 45, 52, 0.96)',
    navInactive: baseTheme.colors.textSecondary,
    navActive: baseTheme.colors.white,
    cardBorder: 'rgba(255, 255, 255, 0.08)',
    successSoft: 'rgba(37, 211, 102, 0.14)',
  },
  spacing: {
    ...baseTheme.spacing,
    xxs: baseTheme.spacing.xs,
    xxl: baseTheme.spacing.section,
  },
  typography: {
    ...baseTheme.typography,
    lineHeights: {
      display: baseTheme.typography.sizes.display,
      h1: baseTheme.typography.sizes.h1 + baseTheme.spacing.sm,
      h2: baseTheme.typography.sizes.h2 + baseTheme.spacing.sm,
      h3: baseTheme.typography.sizes.h3 + baseTheme.spacing.sm,
      body: baseTheme.typography.sizes.body + baseTheme.spacing.sm,
      caption: baseTheme.typography.sizes.caption + baseTheme.spacing.sm,
    },
    letterSpacings: {
      tight: -0.4,
      base: 0,
      wide: 0.8,
    },
  },
  borders: {
    none: 0,
    thin: 1,
  },
  sizes: {
    iconSm: baseTheme.spacing.md,
    iconMd: baseTheme.spacing.lg,
    iconLg: baseTheme.spacing.xl,
    inputHeight: baseTheme.spacing.section / 3,
    buttonMinHeight: baseTheme.spacing.xl + baseTheme.spacing.md,
    heroCardMinHeight: baseTheme.spacing.section,
    tabBarHeight: baseTheme.spacing.section / 2,
    avatar: baseTheme.spacing.xl + baseTheme.spacing.xl,
    badge: baseTheme.spacing.lg + baseTheme.spacing.xs,
  },
  opacity: {
    full: 1,
    subtle: 0.66,
    muted: 0.3,
    faint: 0.2,
  },
  buttons: {
    primary: {
      backgroundColor: baseTheme.colors.primary,
      paddingVertical: 11.2,
      paddingHorizontal: 17.92,
      borderRadius: 44.8,
    },
    outline: {
      backgroundColor: 'transparent',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.66)',
      paddingVertical: 11.2,
      paddingHorizontal: 17.92,
      borderRadius: 44.8,
    },
  },
};

export default theme;
